#!/usr/bin/python3
import os, sys

# Get partion number from command line args
if len(sys.argv) != 2:
    print("Wrong number of arguments. Aborting...")
    print("USAGE:\n> sudo ./reboot-to-partition <partition-number>\nWhere <partition-number> is 2, 3, or 4 (required for this particular SD partitioning)")
    exit()
part_name = sys.argv[1]
if part_name not in ['speaker', 'transmitter', 'paper']:
    print("Invalid partion name. Aborting...")
    exit()

# Rewrite and reboot
os.system("sudo dd if=./data/"+part_name+"_boot.img of=/mmcblk0p1")
os.system("sudo reboot")
