#!/usr/bin/python3
import os

# Install new rc.local file
inFile = open('data/rc.local', 'r')
outFile = open('/etc/rc.local', 'w')
inStr = inFile.read()
outStr=inStr.format(os.getcwd())
outFile.write(outStr)
outFile.close()
inFile.close()
